### ISSUE TITLE
When copying some Chinese text from a PDF, the pasted content turns into characters starting with \u.

### ISSUE THREAD

**Issue by ktech0** [Linus789/wl-clip-persist#9] opened 2024-04-08 07:08 UTC
copy:
![swappy-20240408_150626](https://github.com/Linus789/wl-clip-persist/assets/21327854/90f3396d-8b07-4883-8aff-33f6bfa3db1f)

pasted:
![swappy-20240408_150646](https://github.com/Linus789/wl-clip-persist/assets/21327854/5ef84aac-aa4a-41de-a48c-f0bd00cac772)

**Comment by Linus789** [comment] 2024-04-08 07:16
And I guess this only happens if you run wl-clip-persist? In that case, could you send the logs?
```
RUST_LOG=trace wl-clip-persist --clipboard regular
```

**Comment by ktech0** [comment] 2024-04-08 10:34
I'm add the env but not sure where the log is, as I'm using Firefox as PDF reader. However, when I copy multiple times, sometimes there are no issues—it seems quite unstable. I tried using cliphist to copy content from a PDF within Firefox and the problem didn't occur again. Also, when I switched to the Chrome browser, the issue didn't reappear. It may also be a question of Firefox.

**Comment by Linus789** [comment] 2024-04-30 13:14
@Flrian For whatever reason I'm not able to reproduce this. Logs of a working copy-paste and a bad copy-paste might help.

**Comment by Linus789** [comment] 2024-04-30 22:58
Okay, one difference I notice is that different mime types are requested.

Good one:
```
2024-04-30T22:27:27.699 TRACE Seat 13 > Regular clipboard data source 3: received new request for mime type "UTF8_STRING"
2024-04-30T22:27:27.699 TRACE Seat 13 > Regular clipboard data source 3: received new request for mime type "text/html"
```
UTF8_STRING

Bad one:
```
2024-04-30T22:26:41.205 TRACE Seat 13 > Regular clipboard data source 3: received new request for mime type "TEXT"
2024-04-30T22:26:41.205 TRACE Seat 13 > Regular clipboard data source 3: received new request for mime type "text/html"
```
TEXT

My guess is that either
* VSCode requests the wrong mime type, as TEXT should not be used
* TEXT can be used, but Firefox writes data to it incorrectly
* or TEXT can be used, but VSCode interprets the data incorrectly

But in this case I don't quite understand why wl-clip-persist would influence the outcome. I guess one possibility would be that Firefox writes clipboard data differently if the clipboard request is not triggered immediately for that TEXT mime type. But in this case it could also be possible that it has nothing to do with the requested mime types at all.

By the way, I notice that my VSCodium (1.87.2.24072) consistently requests these mime types:
```
2024-04-30T23:45:18.395 TRACE Seat 45 > Regular clipboard data source 3: received new request for mime type "text/plain;charset=utf-8"
2024-04-30T23:45:18.395 TRACE Seat 45 > Regular clipboard data source 3: received new request for mime type "text/html"
```
Okay, after starting VSCodium **for Wayland** (I used the X11 one before), I can reproduce the issue. Now that I can reproduce the issue, I looked into it a bit further. The text we received from Firefox for the mime type TEXT seems to actually be something like `\uxxxx\uxxxx\uxxxx\uxxxx\uxxxx`. The mime type STRING, and text/plain (but not text/plain;charset=utf-8) seem to have the same contents, by the way. The mime type COMPOUND_TEXT seems to be empty.

So the reason is that VSCode requests different mime types. After looking at Firefox with `WAYLAND_DEBUG=1`, I finally have an idea: Firefox offers the mime types in a specific order, and since wl-clip-persist uses a HashSet the order is not preserved. And VSCode **for Wayland** probably depends on the order of the mime type offers. I guess this is a bug in wl-clip-persist that should be fixed!

**Comment by Linus789** [comment] 2024-05-02 21:33
> Cool! I know its only a minor thing, but still, thank you for taking the time and looking into this.
> 
> And also thank you in general for creating the program. Not being able to paste the copied text after closing an app on wayland was super annoying to me, but I have no reason to use a fully fledged clipboard manager either. So I've been very happily using wl-clip-persist for over a year now!

Thank you for your kind and encouraging words! :)

Could you check if this branch fixes the issue? https://github.com/Linus789/wl-clip-persist/tree/preserve-mime-type-offer-order

**Closed** 2024-05-02 22:12 UTC
